### ISSUE TITLE
Cannot run RasCAL

### ISSUE THREAD

**Issue by MariteCG** [arwelHughes/RasCAL_2019#6]
Hi, I have recently changed my MacBook Pro to the new M1 and when I tried to run RasCAL, I got the following error:
Can anyone help?

debug
Unrecognized function or variable 'abeles_loop_new'.

Error in callReflectivityCalculation (line 130)
simRef =
abeles_loop_new(simXdata(:),slds(:),nbairs(:),nbsubs(:),repeats(:),resolutions(:),ssubs(:));

Error in reflectivity_calculation (line 20)
        problem = callReflectivityCalculation(problem);

Error in rascal (line 57)
reflectivity_calculation();

**Comment by MariteCG** [comment]
This was using Matlab 2019b and using the 2019 version. If I rather used Matlab2014b and rascal 2015 version then I got instead the following error:
>> rascal
Warning: "jxlayer.jar" is already specified on static java path. 
> In javaclasspath>local_validate_dynamic_path at 293
  In javaclasspath>local_javapath at 182
  In javaclasspath at 119
  In javaaddpath at 71
  In rascal at 95 
Warning: "jxlayer.jar" is already specified on static java path. 
> In javaclasspath>local_validate_dynamic_path at 293
  In javaclasspath>local_javapath at 182
  In javaclasspath at 119
  In javaaddpath at 71
  In rascal at 96 
Warning: "jxlayer.jar" is already specified on static java path. 
> In javaclasspath>local_validate_dynamic_path at 293
  In javaclasspath>local_javapath at 182
  In javaclasspath at 119
  In javaaddpath at 71
  In rascal at 97 
Warning: "jxlayer.jar" is already specified on static java path. 
> In javaclasspath>local_validate_dynamic_path at 293
  In javaclasspath>local_javapath at 182
  In javaclasspath at 119
  In javaaddpath at 71
  In rascal at 98 
Warning: "jxlayer.jar" is already specified on static java path. 
> In javaclasspath>local_validate_dynamic_path at 293
  In javaclasspath>local_javapath at 182
  In javaclasspath at 119
  In javaaddpath at 71
  In rascal at 100 
Attempt to execute SCRIPT backsorts as a function:
/Applications/rscl-code_2015_beta_Dev/Rascal_functions/backsorts.m
Error in ==> rascal at 136.>> rascal
Warning: "jxlayer.jar" is already specified on static java path. 
> In javaclasspath>local_validate_dynamic_path at 293
  In javaclasspath>local_javapath at 182
  In javaclasspath at 119
  In javaaddpath at 71
  In rascal at 95 
Warning: "jxlayer.jar" is already specified on static java path. 
> In javaclasspath>local_validate_dynamic_path at 293
  In javaclasspath>local_javapath at 182
  In javaclasspath at 119
  In javaaddpath at 71
  In rascal at 96 
Warning: "jxlayer.jar" is already specified on static java path. 
> In javaclasspath>local_validate_dynamic_path at 293
  In javaclasspath>local_javapath at 182
  In javaclasspath at 119
  In javaaddpath at 71
  In rascal at 97 
Warning: "jxlayer.jar" is already specified on static java path. 
> In javaclasspath>local_validate_dynamic_path at 293
  In javaclasspath>local_javapath at 182
  In javaclasspath at 119
  In javaaddpath at 71
  In rascal at 98 
Warning: "jxlayer.jar" is already specified on static java path. 
> In javaclasspath>local_validate_dynamic_path at 293
  In javaclasspath>local_javapath at 182
  In javaclasspath at 119
  In javaaddpath at 71
  In rascal at 100 
Attempt to execute SCRIPT backsorts as a function:
/Applications/rscl-code_2015_beta_Dev/Rascal_functions/backsorts.m
Error in ==> rascal at 136.

**Comment by maxskoda** [comment]
Hi Marite,

I'm afraid I cannot help you with the specific problem, but a simple
alternative is to use Rascal in IDAaaS. Log in at
https://isis.analysis.stfc.ac.uk/
with your user office login details. Click create and scroll down to
Reflectometry environment. Once created, lauch on VNC and start Rascal from
the Applications menu.
Data transfer is a bit more awkward via
https://data.analysis.stfc.ac.uk/ or using an SCP client.
The advantage is that you can leave it fitting and come back to your
session later.
Let me know if you need further help.

All the best,
Max

**Comment by arwelHughes** [comment]
Hey Marite,
Further to my previous email, it seems Mathworks have only just started supporting M1 Mac's - see this link....

https://uk.mathworks.com/matlabcentral/answers/641925-is-matlab-supported-on-apple-silicon-macs

Can you try updating your Matlab to R2021b, to see if that helps?

Cheers,
Arwel

________________________________

**Comment by MariteCG** [comment]
Hi again

Nope it did not work. Same error:

debug
Unrecognized function or variable 'abeles_loop_new'.

Error in callReflectivityCalculation (line 130)
simRef =
abeles_loop_new(simXdata(:),slds(:),nbairs(:),nbsubs(:),repeats(:),resolutions(:),ssubs(:));

Error in reflectivity_calculation (line 20)
        problem = callReflectivityCalculation(problem);

Error in rascal (line 57)
reflectivity_calculation();
 
>> 

But at least it starts to open rascal (the rascal windows pop out)

Marité

> 28 maj 2021 kl. 11:26 skrev arwelHughes ***@***.***>:
> 
> 
> Hey Marite,
> Further to my previous email, it seems Mathworks have only just started supporting M1 Mac's - see this link....
> 
> https://uk.mathworks.com/matlabcentral/answers/641925-is-matlab-supported-on-apple-silicon-macs
> 
> Can you try updating your Matlab to R2021b, to see if that helps?
> 
> Cheers,
> Arwel
> 
> ________________________________
> From: maxskoda ***@***.***>
> Sent: Thursday, May 27, 2021 12:29 PM
> To: arwelHughes/RasCAL_2019 ***@***.***>
> Cc: Subscribed ***@***.***>
> Subject: Re: [arwelHughes/RasCAL_2019] Cannot run RasCAL (#6)
> 
> 
> Hi Marite,
> 
> I'm afraid I cannot help you with the specific problem, but a simple
> alternative is to use Rascal in IDAaaS. Log in at
> https://isis.analysis.stfc.ac.uk/
> with your user office login details. Click create and scroll down to
> Reflectometry environment. Once created, lauch on VNC and start Rascal from
> the Applications menu.
> Data transfer is a bit more awkward via
> https://data.analysis.stfc.ac.uk/ or using an SCP client.
> The advantage is that you can leave it fitting and come back to your
> session later.
> Let me know if you need further help.
> 
> All the best,
> Max
> 
>

**Comment by arwelHughes** [comment]
Hey Marite,
Okay.... can you check if your site license has access to 'Matlab Coder', then I have a solution for you.
Cheers,
Arwel
________________________________

**Comment by MariteCG** [comment]
Yes, I do! I am installing it now

> 28 maj 2021 kl. 12:22 skrev arwelHughes ***@***.***>:
> 
> 
> Hey Marite,
> Okay.... can you check if your site license has access to 'Matlab Coder', then I have a solution for you.
> Cheers,
> Arwel
> ________________________________
> From: MariteCG ***@***.***>
> Sent: Friday, May 28, 2021 11:07 AM
> To: arwelHughes/RasCAL_2019 ***@***.***>
> Cc: Hughes, Arwel (STFC,RAL,ISIS) ***@***.***>; Comment ***@***.***>
> Subject: Re: [arwelHughes/RasCAL_2019] Cannot run RasCAL (#6)
> 
> 
> Hi again
> 
> Nope it did not work. Same error:
> 
> debug
> Unrecognized function or variable 'abeles_loop_new'.
> 
> Error in callReflectivityCalculation (line 130)
> simRef =
> abeles_loop_new(simXdata(:),slds(:),nbairs(:),nbsubs(:),repeats(:),resolutions(:),ssubs(:));
> 
> Error in reflectivity_calculation (line 20)
> problem = callReflectivityCalculation(problem);
> 
> Error in rascal (line 57)
> reflectivity_calculation();
> 
> >>
> 
> But at least it starts to open rascal (the rascal windows pop out)
> 
> Marité
> 
> > 28 maj 2021 kl. 11:26 skrev arwelHughes ***@***.***>:
> >
> >
> > Hey Marite,
> > Further to my previous email, it seems Mathworks have only just started supporting M1 Mac's - see this link....
> >
> > https://uk.mathworks.com/matlabcentral/answers/641925-is-matlab-supported-on-apple-silicon-macs
> >
> > Can you try updating your Matlab to R2021b, to see if that helps?
> >
> > Cheers,
> > Arwel
> >
> > ________________________________
> > From: maxskoda ***@***.***>
> > Sent: Thursday, May 27, 2021 12:29 PM
> > To: arwelHughes/RasCAL_2019 ***@***.***>
> > Cc: Subscribed ***@***.***>
> > Subject: Re: [arwelHughes/RasCAL_2019] Cannot run RasCAL (#6)
> >
> >
> > Hi Marite,
> >
> > I'm afraid I cannot help you with the specific problem, but a simple
> > alternative is to use Rascal in IDAaaS. Log in at
> > https://isis.analysis.stfc.ac.uk/
> > with your user office login details. Click create and scroll down to
> > Reflectometry environment. Once created, lauch on VNC and start Rascal from
> > the Applications menu.
> > Data transfer is a bit more awkward via
> > https://data.analysis.stfc.ac.uk/ or using an SCP client.
> > The advantage is that you can leave it fitting and come back to your
> > session later.
> > Let me know if you need further help.
> >
> > All the best,
> > Max
> >
> >

**Comment by arwelHughes** [comment]
Okay - sorry I forgot it's half term this week and am taking some days off. Will sort thin on Monday for you!
Cheers,
Arwel

________________________________
